name: Clang format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -qq clang-format
    - name: Check format
      run: ./format-test.sh
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libcurl4-openssl-dev libncursesw5-dev
      - name: build the binary
        run: |
          ./configure
          make
        env:
          CC: gcc
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libcurl4-openssl-dev libncursesw5-dev
      - name: build the binary
        run: |
          ./configure
          make
        env:
          CC: clang
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq check libcurl4-openssl-dev libncursesw5-dev
      - name: build the binary
        run: |
          ./configure
          make
          make test
        env:
          CC: gcc
